CREATE TABLE IF NOT EXISTS Genre ( 
GenreID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, 
GenreName TEXT NOT NULL );

CREATE TABLE IF NOT EXISTS StreamingService (
StreamingServiceID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
ServiceName TEXT NOT NULL );

CREATE TABLE IF NOT EXISTS Playlist ( 
PlaylistID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, 
PlaylistName TEXT NOT NULL,
Link TEXT NOT NULL,
StreamingServiceID INTEGER NOT NULL,
FOREIGN KEY(StreamingServiceID) REFERENCES StreamingService(StreamingServiceID) ON DELETE SET NULL );

CREATE TABLE IF NOT EXISTS Country ( 
CountryID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, 
CountryName TEXT NOT NULL );

CREATE TABLE IF NOT EXISTS City ( 
CityID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, 
CityName TEXT NOT NULL );

CREATE TABLE IF NOT EXISTS GenrePlaylist ( 
GenrePlaylistID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
GenreID INTEGER NOT NULL,
PlaylistID INTEGER NOT NULL, 
FOREIGN KEY(GenreID) REFERENCES Genre(GenreID) ON DELETE SET NULL,
FOREIGN KEY(PlaylistID) REFERENCES Playlist(PlaylistID) ON DELETE SET NULL );

CREATE TABLE IF NOT EXISTS GenreCountry ( 
GenreCountry INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, 
CountryID INTEGER NOT NULL, 
GenreID INTEGER NOT NULL, 
FOREIGN KEY(CountryID) REFERENCES Country(CountryID) ON DELETE SET NULL, 
FOREIGN KEY(GenreID) REFERENCES Genre(GenreID) ON DELETE SET NULL );

CREATE TABLE IF NOT EXISTS GenreCity ( 
GenreCityID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, 
CityID INTEGER NOT NULL, 
GenreID INTEGER NOT NULL,
FOREIGN KEY(CityID) REFERENCES City(CityID) ON DELETE SET NULL, 
FOREIGN KEY(GenreID) REFERENCES Genre(GenreID) ON DELETE SET NULL );

