PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS GenreCity;
DROP TABLE IF EXISTS GenreCountry;
DROP TABLE IF EXISTS GenrePlaylist;
DROP TABLE IF EXISTS City;
DROP TABLE IF EXISTS Country;
DROP TABLE IF EXISTS Playlist;
DROP TABLE IF EXISTS Genre;
DROP TABLE IF EXISTS StreamingService;

PRAGMA foreign_keys = ON;